#!/usr/bin/python3

from code_style_c import checkCCodingStyle
from code_style_haskell import checkHaskellCodingStyle
import sys


args = sys.argv[1:]
c_results = checkCCodingStyle(args)
haskell_results = checkHaskellCodingStyle(args)

errors_sum = c_results[0] + haskell_results[0]

if c_results[2] > 0:
    print("\n\033[96;1mC Style results\033[0m\n")
    print(c_results[1])

if haskell_results[2] > 0:
    print("\n\033[96;1mHaskell Style results\033[0m\n")
    print(haskell_results[1])

if errors_sum == 0:
    print("No errors found")
    exit(0)

err = "errors" if errors_sum > 1 else "error"
print(f"Found {errors_sum} {err}")
exit(0 if "--no-status" in args else 1)

