#!/bin/bash
if [ "$#" == "1" ]; then
  if [ "$1" == "--update" ]; then
    /opt/plum-coding-style/plum_update.sh
    exit 0
  else
    echo -e "Usage: plum [OPTION]\n\nOptions:\n  --update\tUpdate Plum"
    exit 1
  fi
fi
/opt/plum-coding-style/code-style-c
/opt/plum-coding-style/code-style-haskell
